info:
  contact: {}
  description: 个人博客接口列表
  title: blog后端接口
  version: "0.1"
paths:
  /article:
    delete:
      responses: {}
      summary: 删除文章
    get:
      responses: {}
      summary: 获取所有文章
    post:
      responses: {}
      summary: 提交文章
  /comment:
    delete:
      responses: {}
      summary: 删除文章评论
    get:
      responses: {}
      summary: 获取文章评论
    post:
      responses: {}
      summary: 提交文章评论
  /login:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200 ,"msg":"ok"}'
          schema:
            type: string
        "400":
          description: '{"code":400,"msg":"bad request"}'
          schema:
            type: string
        "500":
          description: '{"code":500,"msg":"server error"}'
          schema:
            type: string
      summary: 用户登录接口
  /signin:
    post:
      consumes:
      - application/json
      description: 这是一个用户登录接口
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"msg":"ok"}'
          schema:
            type: string
        "400":
          description: '{"code":400,"msg":"bad request"}'
          schema:
            type: string
        "500":
          description: '{"code":500,"msg":"server error"}'
          schema:
            type: string
      summary: 用户注册接口
swagger: "2.0"
